package ChainOfResponsibility;

/*
 * try {} catch 문에서 사용 
 */

public class testMain {

	public static void main(String[] args) {

		
	}

}
